FROM docker.io/debian:bookworm-slim

RUN <<EOF
#!/usr/bin/env bash

set -euxo pipefail
IFS=$'\n\t'

apt-get update

apt-get install -y --no-install-recommends \
  python3-minimal python3-dnspython python3-requests pylint

# install with recommended depencies for coverage, to include jquery
apt-get install -y python3-coverage pycodestyle

apt-get clean

EOF

USER 1000

WORKDIR /acme_dns_tiny

COPY --chown=${USER}:0 . .
