#after_script:
#    - sleep 10

jessie:
  image: adt-jessie_dnspython3_1.11
  before_script:
    - pip3 install --upgrade -r tests/requirements.txt
  script:
    - coverage run --source ./ -m unittest -v tests.test_acme_dns_tiny tests.test_acme_account_rollover tests.test_acme_account_delete
    - coverage report --include=acme_dns_tiny.py,tools/acme_account_rollover.py,tools/acme_account_delete.py
    - coverage html

jessie_backport:
  image: adt-jessie_dnspython3_1.15-bpo
  before_script:
    - pip3 install --upgrade -r tests/requirements.txt
  script:
    - coverage run --source ./ -m unittest -v tests.test_acme_dns_tiny tests.test_acme_account_rollover tests.test_acme_account_delete
    - coverage report --include=acme_dns_tiny.py,tools/acme_account_rollover.py,tools/acme_account_delete.py
    - coverage html
