ARG DEBIAN_RELEASE=stable

FROM docker.io/debian:${DEBIAN_RELEASE}-slim

RUN <<EOF
#!/usr/bin/env bash

set -euxo pipefail
IFS=$'\n\t'

apt-get update

apt-get install -y --no-install-recommends \
  python3-minimal python3-dnspython python3-requests pylint \
  python3-coverage pycodestyle

apt-get clean

EOF

USER 1000

WORKDIR /app

COPY --chown=${USER}:0 . .
